name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aiken-lang/setup-aiken@v0.1.0
        with:
          version: v1.1.5

      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - run: cd aiken
      - run: aiken fmt --check
      - run: aiken check -D
      - run: aiken build
      - run: cd ..
      - run: npm install
      - run: npm run build